default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  <% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
  <% else %>
  database: droplet_dynamic_pricing_development
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
  port: <%= ENV.fetch('DB_PORT', '5432') %>
  <% end %>

test:
  <<: *default
  database: droplet_dynamic_pricing_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *default
    migrations_paths: db/cable_migrate
    url: <%= ENV['CACHE_DATABASE_URL'] %>
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
    url: <%= ENV['QUEUE_DATABASE_URL'] %>
  cable:
    <<: *default
    migrations_paths: db/cable_migrate
    url: <%= ENV['CABLE_DATABASE_URL'] %>